### ISSUE TITLE
Pycharm Install

### ISSUE THREAD

**Issue by Nauais** [LennyPhoenix/py-discord-sdk#1]
Hi !

as you can see below, pycharm can't install discordSDK,

my program crash when i try to install discord sdk manually.
I don't know if i'm doing something wrong. can I get some help ?

Thank you,
Noé

![image](https://user-images.githubusercontent.com/55959196/100729395-01687c80-33c9-11eb-8076-e7c2edf0427a.png)

**Comment by LennyPhoenix** [comment]
Odd, I don't personally use PyCharm so I'm not sure what the issue would be here. 
Try running the following in command prompt:
```
D:\Prog_Projet\Python\__projets\DISCrich\venv\Scripts\python.exe -m pip install -U discordsdk
```

**Comment by Nauais** [comment]
thank you for your answer ^^
