### ISSUE TITLE
Update Small Image and Large Image Activity Manager

### ISSUE THREAD

**Issue by ParthJadhav** [LennyPhoenix/py-discord-sdk#10]
I tried using :- 

`ActivityAssets.LargeImage = "rpcimg`

where 'rpcimg' is the name of image I uploaded on Discord Developer Portal.

It worked with https://github.com/qwertyquerty/pypresence . But since  Discord-RPC, has been deprecated in favor of new Discord GameSDK. I wanted to use this repo. 

Any help is appreciated.

**Comment by LennyPhoenix** [comment]
How are you setting the activity state? Your code should look something like this:
```py
import discordsdk as dsdk

APPLICATION_ID =  # Insert your application ID here


app = dsdk.Discord(APPLICATION_ID, dsdk.CreateFlags.default)
activity_manager = app.get_activity_manager()


activity = dsdk.Activity()
activity.state = "Activity State Here"
activity.assets.large_image = "Large Image Name Here"

while True:
    time.sleep(1/60)  # Minor delay to give the program some rest time
    app.run_callbacks()
```

**Comment by ParthJadhav** [comment]
Thank you @LennyPhoenix . It works now :)
