### ISSUE TITLE
how to change activity type

### ISSUE THREAD

**Issue by ParthJadhav** [LennyPhoenix/py-discord-sdk#11]
Can I change the activity type to any of the following because by default it shows playing.

![Screenshot 2021-12-05 at 10 00 38 PM](https://user-images.githubusercontent.com/42001064/144754918-a10cecbd-0db8-42bc-8371-a728d4d32156.png)

**Comment by LennyPhoenix** [comment]
No that isn't possible using the SDK.

**Comment by ParthJadhav** [comment]
> No that isn't possible using the SDK.

Thanks for quick reply. I appreciate it.
