### ISSUE TITLE
is_self_mute not working

### ISSUE THREAD

**Issue by Criveratech** [LennyPhoenix/py-discord-sdk#12]
Maybe I'm just stupid but I cant get it to work. I can only manage to get a static Value out of it. Also seems to change to True once I set an Activity.

```py
app = dsdk.Discord(<appid>, dsdk.CreateFlags.default)

voice_manager = app.get_voice_manager()

def on_curr_user_update():
    print(app.get_voice_manager().is_self_mute())

voice_manager.on_settings_update = on_curr_user_update
# Don't forget to call run_callbacks
while 1:
    time.sleep(1/10)
    app.run_callbacks()
```

is my code right now

**Comment by LennyPhoenix** [comment]
The voice manager only interacts with voice lobbies created from the SDK, it does *not* have access to the voice channel the user is connected to via the Discord client. If you want to access information about the Discord client, you will likely have to use the IPC protocol directly.

Join the [Discord developers server](https://discord.gg/discord-developers) and jump to [this message](https://discord.com/channels/613425648685547541/613425918748131338/712788105039708201) for a bit more information on this.

**Comment by Criveratech** [comment]
Alright, so i WAS using it wrong then, my bad.
Thanks for the fast reply tho :)

**Comment by LennyPhoenix** [comment]
No worries :+1:
