### ISSUE TITLE
Running program opens Discord Games Library and closes

### ISSUE THREAD

**Issue by balt-is-you-and-shift** [LennyPhoenix/py-discord-sdk#13]
I tried to run this code:
```py
import discordsdk as dsdk
import time

APP_ID = 123456789 # Fake ID
START_TIME = time.time()

app = dsdk.Discord(APP_ID,dsdk.CreateFlags.default)
activity_manager = app.get_activity_manager()

activity = dsdk.Activity()
activity.state = "Testing discordsdk"

def callback(result):
	if result == dsdk.Result.ok:
		print("Set")
	else:
		raise Exception(result)

activity_manager.update_activity(activity,callback)

while 1:
	time.sleep(15)
	app.run_callbacks()
```
but instead of actually doing anything, it closed the program and brought my Discord app to this screen:
![image](https://user-images.githubusercontent.com/59123926/173459017-2375a0d0-c5d2-4567-82d5-f612ac3800d4.png)
Why is this happening??

**Comment by LennyPhoenix** [comment]
The SDK can be quite temperamental at times. Try using `no_require_discord` instead of `default` in the create flags, and if that doesn't work you might want to try just restarting your PC

**Comment by balt-is-you-and-shift** [comment]
Using no_require_discord ends up with `internal_error: result 4`.

**Comment by LennyPhoenix** [comment]
Code runs fine on my end: I set the APP_ID to `771366171110932490` and changed the `time.sleep` interval to `0.1` seconds instead of 15. The SDK is incredibly buggy and sadly there isn't a huge amount I can do about it, just make sure you are using the DLL from version 2.5.6.

**Comment by balt-is-you-and-shift** [comment]
Seems to work fine after restarting my computer. Weird.
